name: Test Action
on:
  push:
    branches:
      main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Builds the ReSpec HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run respec_action
        uses: webrecorder/markdown-to-respec@v0.3.0
        with:
          ignore: README.md
